# set up pycharm

- name: install snakefood3
  pip:
    name: snakefood3
    state: present

- name: add script to setup pycharm
  template:
    src: pycharm_setup.sh
    dest: /tmp/pycharm_setup.sh
    mode: 0755

- name: execute pycharm_setup.sh
  shell:
    cmd: /tmp/pycharm_setup.sh
    executable: /usr/bin/bash

