# setup support for manim dev including a venv
# we assume virtualenv and virtualenvwrapper are installed

- name: install .deb packages needed by manin
  apt:
    pkg:
    - python3-pip
    - python3-cairo
    - libcairo2-dev
    - python3-dev
    - ffmpeg
    state: present
  become: yes

- name: install pypi-libavwrapper
  pip:
    name: pypi-libavwrapper
    state: present

- name: Recursively change ownership of a directory
  file:
    path: "{{ dest }}"
    state: directory
    
- name: check if repo already cloned
  shell: "/usr/bin/test -d {{ dest }}/manim/.git"
  register: git_cloned

- git:
    repo: "{{ repo }}"
    dest: "{{ dest }}/manim"
  when: git_cloned.rc != 0
    
- name: set up a virtual env using virtualenvwrapper's mkvirtualenv
  shell:
    cmd: ". /usr/share/virtualenvwrapper/virtualenvwrapper_lazy.sh ; mkvirtualenv -a manim -r requirements.txt --python=$(which python3) {{ venv }}"
    chdir: "{{ dest }}"
    creates: "~{{ user }}/.virtualenvs/{{ venv }}"
    executable: /usr/bin/bash

- name: install snakefood3
  pip:
    name: snakefood3
    state: present
    virtualenv: "~{{ user }}/.virtualenvs/{{ venv }}"

- name: run this as a test for correct installation
  shell:
    cmd: ". /usr/share/virtualenvwrapper/virtualenvwrapper_lazy.sh ; workon {{ venv }} ; python3 -m manim example_scenes.py SquareToCircle -pl"
    chdir: "{{ dest }}/manim"
    executable: /usr/bin/bash
  
